version: '3'
services:
  nginx:
    image: nginx
    container_name: leter-nginx    
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
      - ./ssl:/etc/nginx/conf.d/ssl
      
