version: '3'
services:
  # mysql:
  #   container_name: leter-mysql
  #   image: mysql:8
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ../dev_data/mysql_data:/var/lib/mysql
  #     - ./db/mysql_dev_docker.cnf:/etc/mysql/conf.d/mysql.cnf
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
  #     MYSQL_DATABASE: db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: passx
  rails:
    container_name: leter-rails
    build:
      context: ./rails
      # dockerfile: Dockerfile
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./rails:/app
  nginx:
    container_name: leter-nginx
    build: ./nginx
      # context: .
      # # dockerfile: nginx/Dockerfile
    environment:
      NGINX_ENV: development
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/config
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/include:/etc/nginx/conf.d/include
      - ./nginx/xpublic:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/conf.d/ssl

