module Leter
  class Website
    attr_reader :config

    def initialize(config = Leter::AccountConfig.default)
      @config = config
    end

    def build
      #
      # create assets folder and copy all assets
      # generate html with correct slug/folder name structure for every markdown file
      # generate index for every folder with html files? - for every page being built keep a track of name and url
      # and use that to power the index
      # same can apply for sitemap and rss
      
      io = Leter::IO

      index_builder = Leter::IndexBuilder.new(config)

      io.list_files.each do |file|
        markdown = io.read_file(file)

        #TODO same constructor as index_builder 
        page_builder = Leter::PageBuilder.new(markdown, config)

        url_path = Leter::Slug.new(file).to_s

        io.save_file(url_path, page_builder.html) 

        item = Leter::IndexItem.new.tap do |i|
          i.title = page_builder.title
          i.url = url_path
          i.updated_at = File.mtime(file)
        end

        index_builder.add(root_folder(file), item)
      end

      #TODO save index file
      #fix index_builder test
      #test index in website test
      #setup eduardosasso.leter.io and test real use case

      index_builder.run do |index_root, html|
        io.save_file("#{index_root}/index.html", html)
      end
    end

    def clean
      # list all *.md files and get their html names and remove all
      # delete leter assets folder
      # list all index.hrml files and check if it was generated by leter then delete
      # delete all empty folders

      io = Leter::IO

      io.list_files('html').each do |filename|
        html = io.read_file(filename)

        html_parser = Leter::HtmlParser.new(html)

        io.delete_file(filename) if html_parser.powered_by == 'Leter'
      end
    end

    private

    def root_folder(file)
      Pathname(file)
        .dirname
        .split
        .collect(&:to_s)
        .reject{|e| e =~ /^.{1,2}$/}
        .first
    end
  end
end
